### ISSUE TITLE
Using a custom account prefix makes default genesis invalid

### ISSUE THREAD

**Issue by lumtis** [tendermint/fundraising#65]
## Summary of Bug

Hey, this may have not been in the scope of the MVP release. Just wanted to raise this issue. When using a custom account prefix, the chain can't be started because the default genesis is invalid
The `AuctionFeeCollector` param of `fundraising` will include the `cosmos` prefix and therefore `ValidateGenesis` will fail with `invalid account address: cosmos...`

This is particularly surprising because when using `NewRootCmd` of the `spm` package, the config and therefore the address prefix should be sealed at the beginning of each command: https://github.com/tendermint/spm/blob/21d4f153c688f59d02c7cb8d3f076cfafc5a76bd/cosmoscmd/root.go#L129

But when the `DefaultAuctionFeeCollector ` value is converted to bech32 the fetched config still contains `cosmos`prefix https://github.com/tendermint/fundraising/blob/b762bc73707b0dc7d3ee954770141000f87f2474/x/fundraising/types/params.go#L21

This can also be potentially an issue with `NewRootCmd` of `spm` if the config is not sealed before fetching the default genesis for the `init` command

## Version

`v0.1.0`

## Tasks

- Modify default address prefix https://github.com/tendermint/fundraising/blob/b762bc73707b0dc7d3ee954770141000f87f2474/app/app.go#L96
- Try starting a local node `starport chain serve -r`
```
Error: failed to validate genesis state: invalid account address: cosmos1t2gp44cx86rt8gxv64lpt0dggveg98y4ma2wlnfqts7d4m4z70vqrzud4t
```

## References

-
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jaybxyz** [comment]
Thanks for raising the issue. I can reproduce the bug and it is weird that the prefix config is sealed in this [line](https://github.com/tendermint/spm/blob/master/cosmoscmd/prefix.go#L18). Let me take some time to dig into this issue and verify if this stems from the spm package or something the module is missing. 

**UPDATE** 

I suspect that the config is sealed after the `DefaultAuctionFeeCollector` is generated and stored in memory when building the module. Otherwise, it doesn't make sense to me.

**Comment by jaybxyz** [comment]
### Solution Proposal

We can declare `sdk.AccAddress` and stringtify the address in `DefaultParams()`
